apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-helloworl-app
  namespace: spring-boot
  labels:
    app: spring-boot-helloworl-app
spec:
  replicas: 2
  template:
    metadata:
      name: spring-boot-helloworl-app
      labels:
        app: spring-boot-helloworl-app
    spec:
      containers:
        - name: spring-boot-helloworl-app
          image: devopsevangelist/myhelloworld-k8s:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      restartPolicy: Always
  selector:
    matchLabels:
      app: spring-boot-helloworl-app
