apiVersion: v1
kind: Service
metadata:
  name: spring-boot-helloworld-service
  namespace: spring-boot
spec:
  selector:
    app: spring-boot-helloworl-app
  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer